### ISSUE TITLE
Failed to Push

### ISSUE THREAD

**Issue by Cethric** [jsbain/gitview#2] opened 2015-06-16 10:34 UTC
I am currently having issues pushing my repo to github through this program
```<urlopen error [Errno 32] Broken pipe>``` is occuring, this is the first time this error has occured and it was on an attempt to push a large commit so it could just be a bug limiting the number of files that can be commited.

**Comment by jsbain** [comment] 2015-06-17 02:53
There are basically two main reasons this error can happen:
  1) your network is not connected, or you lose connection
  2) github rejects the push

#2 commonly happens if you have made commits to the repo on github that you have not pulled back to the device, then make a commit on your device.  For instance, updating readme.md or license.txt via github will cause a commit to get made in github that is not reflected on your device until you pull.  Then, when you try to push, github rejects the commit, because HEAD in github is not a direct ancestor of the commit you are pushing.  The way to avoid this is to always do a pull before modifying files locally, to make sure you have the latest.

Once you're in this situation, the best way to solve this is to use stash's git version.  You'd use git fetch, then git merge, followed by git push.  I've been meaning to port over some of those features back into gitview, but haven't gotten around to it.

If you are not comfortable with stash, here's the other workaround -- this won't preserve any local commits you've made but not pushed --  but will at least capture your final version.
   1) create a fresh clone from github, into a new folder
   2) copy the modified files from your old repo folder, into the new folder.  
   3) add & commit the modified files
   4) push to github
  5) you can then delete the old repo folder, and rename your new folder to whatever you want

**Comment by Cethric** [comment] 2015-06-17 11:08
I would like to say that it is a network issue because both stash and gitview failed with the same message however I am able to connect to other services in Pythonista. I will try pushing the project from my compuer later this week. Thankyou for the help

**Comment by jsbain** [comment] 2015-06-17 16:31
did you use stash's gift fetch, followed by git merge?  otherwise you will get the same error.

**Comment by jsbain** [comment] 2015-06-17 16:35
see https://omz-forums.appspot.com/pythonista/post/4976860094005248 for a more detailed explanation of how to use fetch/merge/push to fix this issue

**Comment by jsbain** [comment] 2015-06-17 16:47
also, if you post the results of 
``` 
git branch -r
git log -l10
``` 
we can see if we can spot the problem.

**Comment by Cethric** [comment] 2015-06-17 22:39
Stash output:
```
StaSh v0.4.2
[~/Documents]$ cd HTMLEditor-Pythonista
[HTMLEditor-Pythonista]$ git branch -r
origin/gh-pages 59b012b 
origin/proof_of_concept 05aafcf 
origin/master 93dd35a 
[HTMLEditor-Pythonista]$ git log -l10
--------------------------------------------------
commit: 88fbbfcd1757c8e1278b357ffc2166e1565af7c5
merge: 
author: Cethric     <[...]>
committer: Cethric     <[...]>

Update WebDelegate.py

--------------------------------------------------
commit: 35311fc90a2e44d23ce5e149511833027bea2747
merge: 
author: Cethric    <[...]>
committer: Cethric    <[...]>

Update for CodeMirror

--------------------------------------------------
commit: 2235f3448816d2db07a94e8bd234beb70cb8caef
merge: 
author: Cethric   <[...]>
committer: Cethric   <[...]>

Update to use CodeMirror instead of ACE

--------------------------------------------------
commit: 93dd35aa08126518cd813c31983d04a94a1c0af9
merge: 
author: Cethric  <[...]>
committer: Cethric  <[...]>

Update to editor view (There will be a few of these while I work of my main computer)


--------------------------------------------------
commit: a6f1e8ea52f09f688060d34f5edacbe8ef311eae
merge: 7a1a9dec9ac3cbdc78d85ec5e58acc4e9fa78584
author: Cethric  <Cethric@users.noreply.github.com>
committer: Cethric  <Cethric@users.noreply.github.com>

Merge pull request #20 from cclauss/patch-19

A bit cleaner ;-)

--------------------------------------------------
commit: 7a1a9dec9ac3cbdc78d85ec5e58acc4e9fa78584
merge: 
author: cclauss  <cclauss@bluewin.ch>
committer: cclauss  <cclauss@bluewin.ch>

A bit cleaner ;-)

--------------------------------------------------
commit: 1f73b2b2779d42906b2b6c808712662946ee6bb2
merge: 238747e3230179cc0d7c15736e70058a1d42d55a
author: Cethric  <Cethric@users.noreply.github.com>
committer: Cethric  <Cethric@users.noreply.github.com>

Merge pull request #19 from cclauss/patch-18

Link out to open issue

--------------------------------------------------
commit: 238747e3230179cc0d7c15736e70058a1d42d55a
merge: 
author: cclauss  <cclauss@bluewin.ch>
committer: cclauss  <cclauss@bluewin.ch>

Update README.md

--------------------------------------------------
commit: 48837412e48d4633d5c2f15da807813ba86e5763
merge: 
author: Cethric        <Cethric@users.noreply.github.com>
committer: Cethric        <Cethric@users.noreply.github.com>

Update README.md

--------------------------------------------------
commit: 1d16e7adc411a4da457fed22b8a558dd1eda8b3e
merge: 
author: Cethric        <Cethric@users.noreply.github.com>
committer: Cethric        <Cethric@users.noreply.github.com>

Working on a fix for error #18

[HTMLEditor-Pythonista]$ 
```
Note all of the ```[...]``` are were I have removed my personal email. I do not know why gitview even has this email when I have told github not to use the personal email but the 'Cethric@users.noreply.github.com'. Could this be the issue, an iccorect email for the username/password?

**Comment by Cethric** [comment] 2015-06-17 22:41
Output of git fetch and git merge
```
StaSh v0.4.2
[~/Documents]$ cd HTMLEditor-Pythonista
[HTMLEditor-Pythonista]$ git fetch
imported refs/remotes/origin/master 93dd35aa08126518cd813c31983d04a94a1c0af9
imported refs/remotes/origin/gh-pages 59b012b9a105d77669c3a3ca4725205390416bf2
imported refs/remotes/origin/proof_of_concept 05aafcf368f0894e5f305b71f1c16edf20b5121f
imported refs/tags/1.0.0-concept-proof 05aafcf368f0894e5f305b71f1c16edf20b5121f
imported refs/tags/1.0.0 48837412e48d4633d5c2f15da807813ba86e5763
[HTMLEditor-Pythonista]$ git merge
______________________________
stash: <type 'exceptions.TypeError'>: object of type 'NoneType' has no len()
[HTMLEditor-Pythonista]$ git merge
______________________________
stash: <type 'exceptions.TypeError'>: object of type 'NoneType' has no len()
[HTMLEditor-Pythonista]$ 
```

**Comment by jsbain** [comment] 2015-06-18 07:18
re: the email issue, it appears that when you committed 93dd35a from your main computer (per your comment).   Or else you accidentally updated the email in gitview.  whatever you put in the author info in stash or gitview is what gets committed, github doesn't change the author of a commit (it can't -- since the author is part of what gets hashed to create the unique commit id).   I think stash git may cache your login email if you don't provide the author with `git commit`, so if you were using stash for that commit it could explain it..  edit .git/config to update the email that stash will use by default.  gitview uses whatever is in the commit author field.  Anyway, that shouldn't affect problems with push.

Can you set py_traceback=1 in the _DEFAULT_CONFIG (or in your config file if you are using one) so that we can get a usable traceback out of the `git merge` error?

Actually, I forget if gitview properly sets up the remote tracking branch.  Try `git merge origin/master`.

Also, `git branch -rv` should show if origin/master is an ancestor.

**Comment by Cethric** [comment] 2015-06-18 07:49
```
<type 'exceptions.TypeError'>: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/8E34C48C-E448-4E8D-B40A-A5D9C23DF8A5/Documents/git/stash/stash.py", line 1234, in exec_py_file
    execfile(file_path, namespace, namespace)
  File "git/stash/lib/git/git-merge.py", line 220, in <module>
    merge(sys.argv[1:])
  File "git/stash/lib/git/git-merge.py", line 177, in merge
    merge_head = find_revision_sha(repo,result.commit or get_remote_tracking_branch(repo,repo.active_branch))
  File "/private/var/mobile/Containers/Data/Application/8E34C48C-E448-4E8D-B40A-A5D9C23DF8A5/Documents/git/stash/lib/git/gitutils.py", line 45, in find_revision_sha
    if rev in repo:
  File "/var/mobile/Containers/Data/Application/8E34C48C-E448-4E8D-B40A-A5D9C23DF8A5/Documents/site-packages/gittle/gittle.py", line 1219, in __contains__
    return key in self.repo
  File "/var/mobile/Containers/Data/Application/8E34C48C-E448-4E8D-B40A-A5D9C23DF8A5/Documents/site-packages/dulwich/repo.py", line 460, in __contains__
    if len(name) in (20, 40):
TypeError: object of type 'NoneType' has no len()
```
Resolved by;
```
git merge origin/master
______________________________
head is already up to date
[HTMLEditor-Pythonista]$ 
```
My copy seems to be correct
The error of the push has change now to this
```
<type 'exceptions.OSError'>: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/8E34C48C-E448-4E8D-B40A-A5D9C23DF8A5/Documents/git/stash/stash.py", line 1234, in exec_py_file
    execfile(file_path, namespace, namespace)
  File "../git/stash/bin/git.py", line 723, in <module>
    ns.func(args)
  File "../git/stash/bin/git.py", line 565, in git_push
    porcelain.push(repo.repo.path, result.url, branch_name, opener=opener)
  File "/var/mobile/Containers/Data/Application/8E34C48C-E448-4E8D-B40A-A5D9C23DF8A5/Documents/site-packages/dulwich/porcelain.py", line 533, in push
    r.object_store.generate_pack_contents, progress=errstream.write)
  File "/var/mobile/Containers/Data/Application/8E34C48C-E448-4E8D-B40A-A5D9C23DF8A5/Documents/site-packages/dulwich/client.py", line 450, in send_pack
    proto, unused_can_read = self._connect('receive-pack', path)
  File "/var/mobile/Containers/Data/Application/8E34C48C-E448-4E8D-B40A-A5D9C23DF8A5/Documents/site-packages/dulwich/client.py", line 648, in _connect
    stderr=self._stderr))
  File "/private/var/mobile/Containers/Bundle/Application/56740AA4-5D9C-4F5E-9DE9-A297687B7A92/Pythonista.app/pylib/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/private/var/mobile/Containers/Bundle/Application/56740AA4-5D9C-4F5E-9DE9-A297687B7A92/Pythonista.app/pylib/subprocess.py", line 1205, in _execute_child
    self.pid = os.fork()
OSError: [Errno 1] Operation not permitted
```
I will try the push on my main computer and then reclone the repository to my iPad and see if that works.

**Comment by jsbain** [comment] 2015-06-18 08:47
aha.  the old "fork you" issue.

first, `git branch -set-upstream master origin/master` will let you use merge without having to type origin everything.

second, the fork problem is caused by dulwich trying to open a local file, rather than a https.  check `git remote` and make sure you've got the complete address, starting with https:// and ending with .git.
``` git remote origin https://github.com/Cethric/HTMLEditor-Pythonista.git```  should then fix the problem.  be sure to do another git fetch, git merge before pushing.

**Comment by Cethric** [comment] 2015-06-18 08:52
Thank you for the help, it seems to be working again now.

**Closed** 2015-06-20 01:20 UTC
